name: Footbolic CI/CD with Gradle
on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    # application.properties 파일 생성
    - name: Generate Environment Variables File for Production
      run: |
        echo "$APPLICATION_PROPERTIES" >> ./src/main/resources/application.properties
      env:
        APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}

    # gradlew 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # 테스트 Skip 하고 clean build
    - name: Build with Gradle
      run: ./gradlew clean build -x test

    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
        
    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

      # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp ./appspec.yml ./deploy

      # deploy.sh 파일 복사
    - name: Copy deploy.sh
      run: cp ./scripts/deploy.sh ./deploy/scripts

    # zip 파일 생성
    - name: Make zip file
      run: zip -r ./footbolic-test.zip ./deploy
      shell: bash

    # AWS 접근 환경설정
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # Amazon S3에 업로드
    - name: Upload to S3
      run: aws s3 cp ./footbolic-test.zip s3://footbolic-bucket

    # CodeDeploy 실행
    - name: Execute CodeDeploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
          --application-name footbolic-code-deploy-application \
          --deployment-group-name FOOTBOLIC-WAS-CD-GROUP \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=footbolic-bucket,bundleType=zip,key=footbolic-test.zip \
          --region ap-northeast-2